# Generated by Django 2.1.3 on 2018-11-11 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='id',
        ),
        migrations.AlterField(
            model_name='concept',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='concepts', serialize=False, to='snippets.Inquiry'),
        ),
    ]
